In [8]:
# python script to clean our dataset

# Dictionary of all US States
states = {
    "Alabama" : "AL",
    "Alaska" : "AK",
    "Arizona" : "AZ",
    "Arkansas" : "AR",
    "California" : "CA",
    "Colorado" : "CO",
    "Connecticut" : "CT",
    "Delaware" : "DE",
    "Florida" : "FL",
    "Georgia" : "GA",
    "Hawaii" : "HI",
    "Idaho" : "ID",
    "Illinois" : "IL",
    "Indiana" : "IN",
    "Iowa" : "IA",
    "Kansas" : "KS",
    "Kentucky" : "KY",
    "Louisiana" : "LA",
    "Maine" : "ME",
    "Maryland" : "MD",
    "Massachusetts" : "MA",
    "Michigan" : "MI",
    "Minnesota" : "MN",
    "Mississippi" : "MS",
    "Missouri" : "MO",
    "Montana" : "MT",
    "Nebraska" : "NE",
    "Nevada" : "NV",
    "New Hampshire" : "NH",
    "New Jersey" : "NJ",
    "New Mexico" : "NM",
    "New York" : "NY",
    "North Carolina" : "NC",
    "North Dakota" : "ND",
    "Ohio" : "OH",
    "Oklahoma" : "OK",
    "Oregon" : "OR",
    "Pennsylvania" : "PA",
    "Rhode Island" : "RI",
    "South Carolina" : "SC",
    "South Dakota" : "SD",
    "Tennessee" : "TN",
    "Texas" : "TX",
    "Utah" : "UT",
    "Vermont" : "VT",
    "Virginia" : "VA",
    "Washington" : "WA",
    "West Virginia" : "WV",
    "Wisconsin" : "WI",
    "Wyoming" : "WY"
    
}

statecodes = {
    "Alabama" : 1,
    "Alaska" : 2,
    "Arizona" : 4,
    "Arkansas" : 5,
    "California" : 6,
    "Colorado" : 8,
    "Connecticut" : 9,
    "Delaware" : 10,
    "Florida" : 12,
    "Georgia" : 13,
    "Hawaii" : 15,
    "Idaho" : 16,
    "Illinois" : 17,
    "Indiana" : 18,
    "Iowa" : 19,
    "Kansas" : 20,
    "Kentucky" : 21,
    "Louisiana" : 22,
    "Maine" : 23,
    "Maryland" : 24,
    "Massachusetts" : 25,
    "Michigan" : 26,
    "Minnesota" : 27,
    "Mississippi" : 28,
    "Missouri" : 29,
    "Montana" : 30,
    "Nebraska" : 31,
    "Nevada" : 32,
    "New Hampshire" : 33,
    "New Jersey" : 34,
    "New Mexico" : 35,
    "New York" : 36,
    "North Carolina" : 37,
    "North Dakota" : 38,
    "Ohio" : 39,
    "Oklahoma" : 40,
    "Oregon" : 41,
    "Pennsylvania" : 42,
    "Rhode Island" : 44,
    "South Carolina" : 45,
    "South Dakota" : 46,
    "Tennessee" : 47,
    "Texas" : 48,
    "Utah" : 49,
    "Vermont" : 50,
    "Virginia" : 51,
    "Washington" : 53,
    "West Virginia" : 54,
    "Wisconsin" : 55,
    "Wyoming" : 56
    
}

# As states ids include areas outside of our dataset, which technically belong to the US,
# we need to remap these ids to the range from 1 to 50 for ease of access
idconversion = {
    1 : 1,
    2 : 2,
    3 : 4,
    4 : 5,
    5 : 6,
    6 : 8,
    7 : 9,
    8 : 10,
    9 : 12,
    10 : 13,
    11 : 15,
    12 : 16,
    13 : 17,
    14 : 18,
    15 : 19,
    16 : 20,
    17 : 21,
    18 : 22,
    19 : 23,
    20 : 24,
    21 : 25,
    22 : 26,
    23 : 27,
    24 : 28,
    25 : 29,
    26 : 30,
    27 : 31,
    28 : 32,
    29 : 33,
    30 : 34,
    31 : 35,
    32 : 36,
    33 : 37,
    34 : 38,
    35 : 39,
    36 : 40,
    37 : 41,
    38 : 42,
    39 : 44,
    40 : 45,
    41 : 46,
    42 : 47,
    43 : 48,
    44 : 49,
    45 : 50,
    46 : 51,
    47 : 53,
    48 : 54,
    49 : 55,
    50 : 56
    
}

# state population expressed as percentage of total US population
state_population_percentage = {
    1 : 1.48,
    2 : 0.22,
    3 : 2.17,
    4 : 0.91,
    5 : 12.01,
    6 : 1.72,
    7 : 1.08,
    8 : 0.29,
    9 : 6.44,
    10 : 3.18,
    11 : 0.43,
    12 : 0.53,
    13 : 3.85,
    14 : 2.02,
    15 : 0.95,
    16 : 0.88,
    17 : 1.35,
    18 : 1.41,
    19 : 0.40,
    20 : 1.83,
    21 : 2.09,
    22 : 3.02,
    23 : 1.70,
    24 : 0.90,
    25 : 1.85,
    26 : 0.32,
    27 : 0.58,
    28 : 0.92,
    29 : 0.41,
    30 : 2.69,
    31 : 0.63,
    32 : 5.91,
    33 : 3.14,
    34 : 0.23,
    35 : 3.53,
    36 : 1.19,
    37 : 1.27,
    38 : 3.87,
    39 : 0.32,
    40 : 1.54,
    41 : 0.27,
    42 : 2.05,
    43 : 8.80,
    44 : 0.96,
    45 : 0.19,
    46 : 2.58,
    47 : 2.28,
    48 : 0.55,
    49 : 1.76,
    50 : 0.17
}

# Total US population (50 States, no special districts)
us_population = 326464979

inv_map = {v: k for k, v in statecodes.items()}

In [9]:
import re

# replaces the location description with the state (if identifyable)
def repl_location(loc):
    for key in states:
        if (key in loc.lower() or states[key] in loc):
            return key
    return "FALSE"

# replaces the jobtype with one of five categories
def repl_jobtype(jobtype):
    if ("employee" in jobtype.lower()):
        if ("full time" in jobtype.lower()):
            return 'full time employee'
        elif ("part time" in jobtype.lower()):
            return 'part time employee'
        else:
            return 'other'
    elif ("contract" in jobtype.lower()):
        if ("full time" in jobtype.lower()):
            return 'full time contractor'
        else:
            return 'other'
    elif (jobtype == None):
        return 'None'
    else:
        return 'other'

# parses the salary
def parse_salary(salary):
    yearly = False
    lower = None
    upper = None
    
    if ("year" in salary.lower()):
        yearly = True
        lower = re.search("^[0-9]*[,]*[0-9]+[.]00.[-]", salary)
        if (lower != None):
            lower = lower.group()[:-2]
            lower = float(lower.replace(',', ''))
        upper = re.search("[0-9]*[,]*[0-9]+[.]00.[$]", salary)
        if (upper != None):
            upper = upper.group()[:-2]
            upper = float(upper.replace(',', ''))
    elif ("hour" in salary.lower()):
        lower = re.search("^[0-9]+[.]00.[-]", salary)
        if (lower != None):
            lower = lower.group()[:-2]
            lower = float(lower.replace(',', ''))
        upper = re.search("[0-9]+[.]00.[$]", salary)
        if (upper != None):
            upper = upper.group()[:-2]
            upper = float(upper.replace(',', ''))
    return [yearly, lower, upper]

In [14]:
import csv

# The dirty/uncleaned dataset
infile = '/home/vincent/Documents/programming/VisualizationFinalProject/jobsMap/src/dataset/us-jobs-on-monstercom/monster_com-job_sample.csv'

# open the CSV and run over all rows, calling the various replacement and parsing functions
f = open(infile)
csv_f = csv.reader(f)

rowcount = 0
rows = []

for row in csv_f:
    newrow = []
    if (rowcount != 0):
        #replace location
        row[8] = repl_location(row[8])
        if (row[8] != "FALSE"):
            newrow.append(row[8])
            newrow.append(statecodes[row[8]])
        #replace jobtype
        newrow.append(repl_jobtype(row[7]))
        #parse salary
        parsed_salary = parse_salary(row[11])
        newrow.append(parsed_salary[0])
        newrow.append(parsed_salary[1])
        newrow.append(parsed_salary[2])
        
        #add organization, sector and job title to new row
        newrow.append(row[9].replace(',', ''))
        newrow.append(row[12].replace(',', ''))
        newrow.append(row[6].replace(',', ''))
        
        #add newrow to rows to be written into the cleaned dataset
        rows.append(newrow)
    rowcount += 1

In [15]:
outfile = '/home/vincent/Documents/programming/VisualizationFinalProject/jobsMap/src/dataset/us-jobs-on-monstercom/cleaned_data.csv'

fields = ['location', 'id', 'job_type', 'yearly', 'salary_lower', 'salary_upper', 'organization', 'sector', 'job_title']

# writing to csv file 
with open(outfile, 'w') as csvfile: 
    # creating a csv writer object 
    csvwriter = csv.writer(csvfile) 
      
    # writing the fields 
    csvwriter.writerow(fields) 
      
    # writing the data rows 
    csvwriter.writerows(rows)